import operator
from dataclasses import dataclass
from typing import Annotated, TypedDict


# TODO: separate input and output schemas
@dataclass
class InputPlanningState(TypedDict):
    pass


@dataclass
class PlanningState(TypedDict):
    """State of conversation between Agent and User."""

    project_idea: str  # Initial idea of the project
    clarifying_questions_from_agent: Annotated[
        list[str], operator.Add
    ]  # Clarifying questions to refine the project idea
    user_questions: Annotated[
        list[str], operator.Add
    ]  # question from user to clarify/ask for details
    project_plan: Annotated[list[str], operator.Add]  # generated by Agent/s
